version: '3.8'

services:
  frontend:
    build: ./frontend
    ports: 
      - 4200:4200
  backend:
    image: eduperes/angular-python-project-backend
    depends_on:
      - database
    build: ./backend
    environment:
      - ENV_FILE_PATH=environments/.env.${SHORT_ENV}
    ports:
      - 8000:8000
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn src.api:app --host 0.0.0.0 --port 8000"
  database:
    image: eduperes/angular-python-project-database
    build: ./database
    ports:
      - 3308:3306
    # volumes:
    #   - ./database_volume:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=12345

volumes:
  database_volume:


