version: '3.8'

services:  
  frontend:
    image: eduperes/edustore-frontend
    build: 
      context: ./frontend
      no_cache: true #Set to true to make a clean build
    ports: 
      - 4200:4200
  backend:
    image: eduperes/edustore-backend
    depends_on:
      - database
    build: 
      context: ./backend
      no_cache: true #Set to true to make a clean build
    environment:
      - ENV_FILE_PATH=environments/.env.${SHORT_ENV}
    ports:
      - 8000:8000
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn src.api:app --host 0.0.0.0 --port 8000"
    restart: 'always'
  database:
    image: eduperes/edustore-database
    build: ./database
    ports:
      - 3308:3306
    # volumes:
    #   - ./database_volume:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=12345

volumes:
  database_volume:


